"""empty message

Revision ID: a3e9923f2e1b
Revises: d939c7470a66
Create Date: 2025-11-26 23:57:16.656367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e9923f2e1b'
down_revision = 'd939c7470a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('comments_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_from_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_to_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('follow_followed_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('follow_following_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_to_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_from_id'], ['id'])
        batch_op.drop_column('following_id')
        batch_op.drop_column('followed_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('following_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('follow_following_id_fkey', 'users', ['following_id'], ['id'])
        batch_op.create_foreign_key('follow_followed_id_fkey', 'users', ['followed_id'], ['id'])
        batch_op.drop_column('user_to_id')
        batch_op.drop_column('user_from_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
